import type { Subject } from './types'

export const subjects: Subject[] = [
  {
    id: 'subject-math',
    title: 'Математика',
    description: 'Алгебра, геометрия и подготовка к экзаменам.',
    icon: 'calculator',
    progress: 72,
    completedTopics: 18,
    totalTopics: 25,
    requiredTopics: 20,
    completedRequiredTopics: 16,
  },
  {
    id: 'subject-history',
    title: 'История Казахстана',
    description: 'Ключевые события и личности от древности до современности.',
    icon: 'landmark',
    progress: 48,
    completedTopics: 12,
    totalTopics: 25,
    requiredTopics: 18,
    completedRequiredTopics: 9,
  },
  {
    id: 'subject-physics',
    title: 'Физика',
    description: 'Понятия, формулы и задачи для уверенного понимания предмета.',
    icon: 'flask-conical',
    progress: 26,
    completedTopics: 5,
    totalTopics: 19,
    requiredTopics: 15,
    completedRequiredTopics: 4,
  },
  {
    id: 'subject-biology',
    title: 'Биология',
    description: 'Клетка, генетика и основы физиологии человека.',
    icon: 'flask-conical',
    progress: 61,
    completedTopics: 11,
    totalTopics: 18,
    requiredTopics: 14,
    completedRequiredTopics: 9,
  },
  {
    id: 'subject-kazakh-language',
    title: 'Казахский язык',
    description: 'Грамматика, синтаксис и практика грамотной речи.',
    icon: 'languages',
    progress: 37,
    completedTopics: 7,
    totalTopics: 19,
    requiredTopics: 15,
    completedRequiredTopics: 6,
  },
  {
    id: 'subject-informatics',
    title: 'Информатика',
    description: 'Алгоритмы, программирование и цифровая грамотность.',
    icon: 'book-open',
    progress: 84,
    completedTopics: 21,
    totalTopics: 25,
    requiredTopics: 22,
    completedRequiredTopics: 20,
  },
]
