import type { Lesson } from './types'

export const currentLesson: Lesson = {
  id: 'lesson-quadratic-equations',
  subjectId: 'subject-math',
  title: 'Квадратные уравнения',
  description: 'Разбираем дискриминант и учимся находить корни квадратного уравнения.',
  duration: 24,
  completed: false,
  required: true,
  progress: 64,
  notes:
    'Квадратное уравнение имеет вид ax² + bx + c = 0. Для поиска корней сначала вычисляем дискриминант, а затем выбираем подходящую формулу.',
  timecodes: [
    { id: 'intro', label: 'Введение', time: '00:00' },
    { id: 'formula', label: 'Формула дискриминанта', time: '06:42' },
    { id: 'practice', label: 'Практика', time: '15:10' },
    { id: 'summary', label: 'Итоги', time: '21:40' },
  ],
}

export const lessons: Lesson[] = [
  {
    id: 'lesson-linear-equations',
    subjectId: 'subject-math',
    title: 'Линейные уравнения',
    description: 'Повторяем свойства равенств и решаем уравнения в несколько действий.',
    duration: 18,
    completed: true,
    required: true,
    progress: 100,
    notes:
      'Линейное уравнение содержит переменную только в первой степени. Главное правило — выполнять одинаковые действия с обеими частями.',
    timecodes: [
      { id: 'linear-intro', label: 'Что такое уравнение', time: '00:00' },
      { id: 'linear-rules', label: 'Правила преобразований', time: '05:20' },
      { id: 'linear-practice', label: 'Разбор задач', time: '11:45' },
    ],
  },
  currentLesson,
  {
    id: 'lesson-functions',
    subjectId: 'subject-math',
    title: 'Функции и графики',
    description: 'Учимся читать графики и находить зависимость между величинами.',
    duration: 31,
    completed: false,
    required: true,
    progress: 22,
    notes: 'Функция связывает каждое значение аргумента с единственным значением функции.',
    timecodes: [
      { id: 'functions-intro', label: 'Аргумент и функция', time: '00:00' },
      { id: 'functions-graph', label: 'Как читать график', time: '12:14' },
      { id: 'functions-practice', label: 'Практическая задача', time: '24:05' },
    ],
  },
  {
    id: 'lesson-trigonometry',
    subjectId: 'subject-math',
    title: 'Основы тригонометрии',
    description: 'Синус, косинус и тангенс в прямоугольном треугольнике.',
    duration: 27,
    completed: false,
    required: false,
    progress: 0,
    notes:
      'Тригонометрические отношения помогают связать углы и стороны прямоугольного треугольника.',
    timecodes: [
      { id: 'trig-intro', label: 'Прямоугольный треугольник', time: '00:00' },
      { id: 'trig-ratios', label: 'Основные отношения', time: '09:30' },
      { id: 'trig-example', label: 'Пример решения', time: '19:12' },
    ],
  },
  {
    id: 'lesson-kazakh-khanate',
    subjectId: 'subject-history',
    title: 'Образование Казахского ханства',
    description: 'Предпосылки создания ханства и роль Керея и Жанибека.',
    duration: 22,
    completed: true,
    required: true,
    progress: 100,
    notes:
      'Казахское ханство сформировалось в XV веке после отделения Керея и Жанибека от государства Абулхаира.',
    timecodes: [
      { id: 'kh-history', label: 'Исторический контекст', time: '00:00' },
      { id: 'kh-founders', label: 'Керей и Жанибек', time: '08:10' },
      { id: 'kh-result', label: 'Значение события', time: '17:40' },
    ],
  },
  {
    id: 'lesson-golden-horde',
    subjectId: 'subject-history',
    title: 'Золотая Орда',
    description: 'Государственное устройство, торговые пути и культурное наследие.',
    duration: 29,
    completed: false,
    required: true,
    progress: 48,
    notes:
      'Золотая Орда была крупным государством Евразии, контролировавшим важные торговые маршруты.',
    timecodes: [
      { id: 'orda-state', label: 'Возникновение государства', time: '00:00' },
      { id: 'orda-trade', label: 'Торговля и города', time: '13:25' },
      { id: 'orda-legacy', label: 'Историческое наследие', time: '23:40' },
    ],
  },
  {
    id: 'lesson-kazakhstan-20c',
    subjectId: 'subject-history',
    title: 'Казахстан в XX веке',
    description: 'Главные события и изменения общественной жизни Казахстана.',
    duration: 35,
    completed: false,
    required: false,
    progress: 0,
    notes:
      'В уроке собраны ключевые этапы истории Казахстана XX века и их влияние на современность.',
    timecodes: [
      { id: '20c-overview', label: 'Обзор периода', time: '00:00' },
      { id: '20c-events', label: 'Основные события', time: '16:08' },
      { id: '20c-summary', label: 'Вопросы для повторения', time: '29:20' },
    ],
  },
  {
    id: 'lesson-motion',
    subjectId: 'subject-physics',
    title: 'Равномерное движение',
    description: 'Скорость, путь и время: строим модели движения и читаем графики.',
    duration: 21,
    completed: true,
    required: true,
    progress: 100,
    notes:
      'При равномерном движении тело за равные промежутки времени проходит одинаковые расстояния.',
    timecodes: [
      { id: 'motion-values', label: 'Путь, время, скорость', time: '00:00' },
      { id: 'motion-formula', label: 'Основная формула', time: '07:24' },
      { id: 'motion-task', label: 'Задача на движение', time: '15:36' },
    ],
  },
  {
    id: 'lesson-newtons-laws',
    subjectId: 'subject-physics',
    title: 'Законы Ньютона',
    description: 'Разбираем связь силы, массы и ускорения на понятных примерах.',
    duration: 34,
    completed: false,
    required: true,
    progress: 34,
    notes: 'Законы Ньютона описывают, как силы изменяют движение тел.',
    timecodes: [
      { id: 'newton-first', label: 'Первый закон', time: '00:00' },
      { id: 'newton-second', label: 'Второй закон', time: '12:30' },
      { id: 'newton-third', label: 'Третий закон', time: '25:15' },
    ],
  },
  {
    id: 'lesson-energy',
    subjectId: 'subject-physics',
    title: 'Работа и энергия',
    description: 'Потенциальная и кинетическая энергия в повседневных ситуациях.',
    duration: 26,
    completed: false,
    required: false,
    progress: 0,
    notes:
      'Энергия показывает способность системы совершать работу и может переходить из одной формы в другую.',
    timecodes: [
      { id: 'energy-work', label: 'Механическая работа', time: '00:00' },
      { id: 'energy-kinetic', label: 'Кинетическая энергия', time: '10:18' },
      { id: 'energy-potential', label: 'Потенциальная энергия', time: '19:44' },
    ],
  },
  {
    id: 'lesson-cell',
    subjectId: 'subject-biology',
    title: 'Строение клетки',
    description: 'Органоиды клетки и их функции в жизнедеятельности организма.',
    duration: 25,
    completed: true,
    required: true,
    progress: 100,
    notes: 'Клетка — структурная и функциональная единица живого организма.',
    timecodes: [
      { id: 'cell-membrane', label: 'Мембрана и цитоплазма', time: '00:00' },
      { id: 'cell-nucleus', label: 'Ядро клетки', time: '09:05' },
      { id: 'cell-organelles', label: 'Органоиды', time: '17:50' },
    ],
  },
  {
    id: 'lesson-genetics',
    subjectId: 'subject-biology',
    title: 'Основы генетики',
    description: 'Гены, признаки и простые закономерности наследования.',
    duration: 32,
    completed: false,
    required: true,
    progress: 52,
    notes: 'Генетика изучает наследственность и изменчивость организмов.',
    timecodes: [
      { id: 'genetics-terms', label: 'Основные термины', time: '00:00' },
      { id: 'genetics-mendel', label: 'Законы Менделя', time: '14:22' },
      { id: 'genetics-practice', label: 'Решение задач', time: '25:30' },
    ],
  },
  {
    id: 'lesson-kazakh-parts',
    subjectId: 'subject-kazakh-language',
    title: 'Части речи',
    description: 'Распознаём самостоятельные и служебные части речи в предложении.',
    duration: 19,
    completed: true,
    required: true,
    progress: 100,
    notes: 'Части речи различаются по значению, грамматическим признакам и роли в предложении.',
    timecodes: [
      { id: 'parts-noun', label: 'Зат есім', time: '00:00' },
      { id: 'parts-verb', label: 'Етістік', time: '07:16' },
      { id: 'parts-practice', label: 'Практика', time: '14:40' },
    ],
  },
  {
    id: 'lesson-kazakh-syntax',
    subjectId: 'subject-kazakh-language',
    title: 'Синтаксис простого предложения',
    description: 'Главные члены предложения и порядок слов в казахском языке.',
    duration: 28,
    completed: false,
    required: true,
    progress: 18,
    notes: 'В простом предложении важно определить грамматическую основу и смысловые связи слов.',
    timecodes: [
      { id: 'syntax-base', label: 'Грамматическая основа', time: '00:00' },
      { id: 'syntax-order', label: 'Порядок слов', time: '11:05' },
      { id: 'syntax-task', label: 'Разбор предложения', time: '21:30' },
    ],
  },
  {
    id: 'lesson-algorithms',
    subjectId: 'subject-informatics',
    title: 'Алгоритмы и блок-схемы',
    description: 'Описываем последовательность действий и находим ветвления.',
    duration: 23,
    completed: true,
    required: true,
    progress: 100,
    notes: 'Алгоритм — точное описание действий, которые приводят к решению задачи.',
    timecodes: [
      { id: 'algo-properties', label: 'Свойства алгоритма', time: '00:00' },
      { id: 'algo-flowchart', label: 'Блок-схемы', time: '08:45' },
      { id: 'algo-practice', label: 'Практическая задача', time: '17:20' },
    ],
  },
  {
    id: 'lesson-python-basics',
    subjectId: 'subject-informatics',
    title: 'Основы Python',
    description: 'Переменные, условия и циклы на первых практических примерах.',
    duration: 38,
    completed: false,
    required: true,
    progress: 68,
    notes: 'Python позволяет описывать алгоритмы понятным и лаконичным кодом.',
    timecodes: [
      { id: 'python-values', label: 'Переменные и типы', time: '00:00' },
      { id: 'python-if', label: 'Условные операторы', time: '14:40' },
      { id: 'python-loops', label: 'Циклы', time: '27:15' },
    ],
  },
]
